#author : manch1n
# discription : if prefix is "##" ,this means that you should keep it and do not delete the prefix

STANDARD=-std=c11
OPTIMIZE=-O2
build: #dependency file(you should replace it)
	#example: mpicc $(MKARG) $(STANDARD) -o exer_3_4.out exer_3_4.c
	mpicc $(MKARG) $(STANDARD) -o exer_3_11.out exer_3_11.c
clean:
	rm -rf *.out